-- V14__Remove_broadband_and_water.sql

DELETE FROM fact_value
WHERE metric_id IN ('BROADBAND_COVERAGE_PERCENT', 'WATER_QUALITY_COMPLIANCE_PERCENT')
   OR source_id IN ('FCC_BROADBAND', 'EPA_WATER');

DELETE FROM source_run
WHERE source_id IN ('FCC_BROADBAND', 'EPA_WATER');

DELETE FROM source_config
WHERE source_id IN ('FCC_BROADBAND', 'EPA_WATER');

DELETE FROM source
WHERE source_id IN ('FCC_BROADBAND', 'EPA_WATER');

DELETE FROM metric
WHERE metric_id IN ('BROADBAND_COVERAGE_PERCENT', 'WATER_QUALITY_COMPLIANCE_PERCENT');
